
services:
  redis:
   image: redis:7-alpine

  mailhog:
    image: mailhog/mailhog

  api:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      SMTP_HOST: mailhog
      SMTP_PORT: "1025"
      SMTP_FROM: no-reply@example.com

    depends_on:
      - redis
      - mailhog
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  
  worker:
    build: .
    command: celery -A celery_app worker -l info
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      - redis
    volumes:
      - .:/app